---
title: "Figures for NTI Paper"
author: "Sailor Miao"
date: "2023-8-15"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

## For the figures in the paper, we used R studio as well as the Global Health Security Index's Data Model, which allowed us to perform correlation analysis. To download the Model, please consult https://www.ghsindex.org/report-model/ . In addition, we used graphic design tool Canva and Microsoft Word and Excel for data processing and aesthetic processes. 

##  First, I imported the GHS Index published on NTI's website here.
library(ggplot2)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggraph)
library(RColorBrewer)
library(wordcloud)
library(wordcloud2)
library(treemapify)
library(viridisLite)
library(packcircles)
library(igraph)

GHSI <- read.csv("/Users/miaoyidong/Desktop/NTIPaper/Data/2021-GHS-Index-April-2022.csv")


#Because only a few fields are needed, I filtered out ones that are not required. 
new <- GHSI %>% select(Country, Year, OVERALL, PREVENTION, EARLY, RAPID, SUFFICIENT,COMMITMENTS)

##Then, I changed the format from a wide to a long format for processing. 
GHSI_long <- gather(new, biosecurity, score, PREVENTION, EARLY, RAPID, SUFFICIENT, COMMITMENTS)


#Figure 1: Dendrogram ranking averages of indicators by category in the Global Health Security Index
  
##To increase efficiency, we manually reorganized the data to omit irrelevant information. Chart_three includes calculated average scores from all indicators of the 5 categories. For instance, the global average score for AMR surveillance (Prevention category) is 28.44820513. Chart_three_simple is the long format of the document, which is a necessary component of the dendrogram.
  
chart_three<- read.csv("/Users/miaoyidong/Desktop/NTIPaper/Data/chart_three.csv")
chart_three_simple <- read.csv("/Users/miaoyidong/Desktop/NTIPaper/Data/chart_three_simple.csv")

chart_three <- chart_three %>%mutate(word = ifelse(Level == 3, Name, NA))
chart_three <- chart_three %>%mutate(cat = ifelse(Level == 3, Name, NA))
chart_graph <- graph_from_data_frame(chart_three_simple,vertices = chart_three)

#Here, we use the igraph function to structure the figure. 
ggraph(chart_graph, 'igraph',
       algorithm = 'tree',
       circular = TRUE) + 

  geom_edge_diagonal(aes(alpha = ..index..)) +
  coord_fixed() + 
  geom_node_point(aes(filter = degree(chart_graph, mode = 'out') == 0), 
                  color = 'steelblue', size = 1) +
  ggforce::theme_no_axes()


chart_three$Category <- as.factor(chart_three$Category)


chart_three$id <- NA
myleaves <- which(is.na( match(chart_three$Name, chart_three_simple$Strategy) ))
nleaves <- length(myleaves)

# Specify ordering of categories
chart_three$Category <- factor(chart_three$Category,levels = c('', 'PREVENTION', 'RAPID', 'EARLY', 'SUFFICIENT', 'COMMITMENTS'))
# Sort by category and within category by descending count
chart_three <- chart_three[ with(chart_three, order(Category, -Avg_score)),]

 # Assign sequence number to leaves, from which we can assign initial angle
chart_three$id[ myleaves ] <- seq(1:nleaves)
chart_three$angle <- 90 - 360 * chart_three$id / nleaves


chart_three$hjust <- ifelse(chart_three$angle < -90, 1, 0)
chart_three$angle <- ifelse(chart_three$angle < -90, 
                               chart_three$angle + 180, 
                               chart_three$angle)

chart_graph <- graph_from_data_frame(chart_three_simple,vertices = chart_three)

ggraph(chart_graph, layout = 'dendrogram', circular = TRUE) + geom_edge_diagonal(colour="grey") +scale_edge_colour_distiller(palette = "RdPu") +geom_node_point(aes(x = x*1.07, y=y*1.07, colour=Category, filter = leaf, size=Avg_score, alpha=0.2))+scale_color_manual(values = c("black","#088F8F", "#99ff66", "#FF9966", "#33CCCC"))+scale_size_continuous( range = c(0.1,10) )+theme_void() +theme(legend.position="none",plot.margin=unit(c(0,0,0,0),"cm"),)+expand_limits(x = c(-1.1, 1.1), y = c(-1.1, 1.1))


#Figure 2: GHSI score change by country from 2019-2021. 

#We changed the format of the document to a wide format for processing. 
GHSI_wide <- reshape(GHSI_long, idvar = "Country", timevar = "Year", direction = "wide")

# Since we are showing change of scores from 2019-2021, it is important to calculate the difference of the scores between 2019 and 2021. 
GHSI_Difference<- GHSI_wide  %>% group_by(Country) %>% mutate(Difference.Overall=(OVERALL.2021-OVERALL.2019), Difference.perc=(OVERALL.2021-OVERALL.2019)/OVERALL.2019*100) %>% select(Country, OVERALL.2021, Difference.Overall, Difference.perc)

#Here we can see the rank of all countries. 
GHSI_Difference%>% arrange(desc(Difference.Overall))

#Since we wanted to highlight 15 countries with "positive difference" (improvement), we needed to filter out the rest.
GHSI_Difference$highlight <- "NO"
index <- order(GHSI_Difference$Difference.Overall, decreasing = TRUE)[1:15]
GHSI_Difference$highlight[index] <- "Yes"

# A simple dot graph suffices. 
p0 <- ggplot(data =GHSI_Difference, mapping = aes(x = Difference.Overall, y = OVERALL.2021, color = as.factor(highlight)))

# We put country and other important labels by using the annotate function.
p1 <- p0 + geom_point(alpha = 0.6, size=5) +scale_x_continuous(labels=scales::comma, limits=c(-11, 11)) +scale_color_manual(values = c("dodgerblue2","red"))+geom_vline(xintercept=0, linetype=2)+xlab(label="Trend (Change Between 2019-2021)")+ylab(label="GHSI Score in 2021")+theme_bw()+annotate("rect", xmin = -11, xmax = 0, ymin = 0, ymax = 80,alpha = .2)+annotate("text", x=-5.5, y=3, label= "Deterioration", size=5, fontface=2, family="Times New Roman")+annotate("text", x=5.5, y=3, label= "Improvement", size=5, fontface=2, family="Times New Roman")+annotate("text", x=1.9, y=78, label= "United States", size=3, fontface=2, family="Times New Roman")+annotate("text", x=9.4, y=45.1, label= "Brunei", size=3, family="Times New Roman")+annotate("text", x=8.5, y=64.5, label= "New Zealand", size=3,  family="Times New Roman")+annotate("text", x=8.2, y=23, label= "Marshall Islands", size=3,  family="Times New Roman")+annotate("text", x=3.8, y=63, label= "Lithuania", size=3,  family="Times New Roman")+annotate("text", x=7, y=27, label= "Palau", size=3,  family="Times New Roman")+annotate("text", x=4, y=23, label="Kiribati", size=3,  family="Times New Roman")+annotate("text", x=5.6, y=54.7, label="Georgia", size=3,  family="Times New Roman")+annotate("text", x=5.5, y=37, label="Andorra", size=3,  family="Times New Roman")+annotate("text", x=5, y=31.5, label="Angola", size=3,  family="Times New Roman")+annotate("text", x=4.7, y=48.7, label="Qatar", size=3,  family="Times New Roman")+ theme(legend.position = "none")+theme(text = element_text(family = "Times New Roman"))+annotate("text", x=-3.5, y=73, label="Australia", size=3,  fontface=2, family="Times New Roman")+annotate("text", x=0.15, y=72, label="Finland", size=3,  fontface=2, family="Times New Roman")+annotate("text", x=3.2, y=72, label="Canada", size=3,  fontface=2, family="Times New Roman")+annotate("text", x=0.65, y=69, label="Thailand", size=3,  fontface=2, family="Times New Roman")
p1

```


